### ISSUE TITLE
android.app.Fragment

### ISSUE THREAD

**Issue by mindrunner** [first087/Android-License-Fragment#1]
Hi, my app uses the non-support Fragment classes. To use this Library i copied LicenseFragmentBase and RecyclerViewLicenseFragment into my project and swapped the Fragment import statement in the base class. This is kind of annoying. Is there anything to make a library/app more generic to be able to support both Fragments?

**Comment by first087** [comment]
This library depend on Support v4

Fragment class use from android.support.v4.app.Fragment

Your app use Fragment from android.app.Fragment ?

**Comment by mindrunner** [comment]
Yes, exactly!

**Comment by first087** [comment]
OK. I will make new version for support android.app.Fragment

**Comment by mindrunner** [comment]
Cool, that sounds pretty good! :) Thank you for the quick support!

**Comment by first087** [comment]
@mindrunner plz test version 1.1.0

**Comment by mindrunner** [comment]
works!! :) Thank you!

**Comment by first087** [comment]
@mindrunner Please give your app link to me after publish to Play Store. I will add link you your app in README.md for showcase.

**Comment by mindrunner** [comment]
Yeah sure, will need some time though. Still early stage! ;)
