### ISSUE TITLE
Feature request: add custom license with "unknown" license type (e.g. EPL)

### ISSUE THREAD

**Issue by AmiableAnteater** [first087/Android-License-Fragment#3]
Hi *,

first of all - thank you very much for supplying the library.

I'd like to add an entry for an EPL licensed library, i.e. add the copyright and the complete text of the EPL - but as far as I can see, there is no way to achieve this apart from deriving a subclass of `License` and overriding `getLicense()`. But then again this might be the intended way to do it.

All the best and kind regards
AZ

**Comment by first087** [comment]
Please tell me for EPL License format.

Or example for show EPL License.

**Comment by AmiableAnteater** [comment]
Well, the EPL (Eclipse Public License) is [available here](https://www.eclipse.org/legal/epl-v10.html). 
I'm using an EPL library as stated in the Definitions 1/b/ii - I don't derive from the library, my program is encapsuled in different modules.

Problem is - I am not a lawyer. What I'd do is to display the copyright notice of the library and the full text of the license, as well as the required disclaimers and the exclusion of warranties regarding the functionality of the library.

I have (as of now) not found and example of a program that uses an EPL library and displays information about it.

**Comment by first087** [comment]
@andreaszielke Please update to v1.2.0

Sorry for late.
