### ISSUE TITLE
ไม่ควรใช้ anroid:allowBackup ใน Library 

### ISSUE THREAD

**Issue by piruin** [first087/Android-License-Fragment#4]
ผมใช้ Library นี้แล้วเจอปัญหาตามนี้ครับ
`Error:Gradle: Execution failed for task ':app:processDebugManifest'.

> Manifest merger failed : Attribute application@allowBackup value=(false) from AndroidManifest.xml:40:13-40
>     is also present at [com.artit-k:license-fragment:1.1.0] AndroidManifest.xml:11:18-44 value=(true).
>     Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:38:5-126:19 to override.`

ลองทำตาม Suggestion ที่ให้เพิ่ม  `tools:replace="android:allowBackup"` แล้วก็ไม่ช่วยครับ คิดว่าคงเป็นเพราะ bug ของ Android Gradle 

ดังนั้นช่วยเอา attribute นี้ออกจาก Library ได้หรือไม่ครับ  เพราะตัว Library ไม่ควรจะบังคับให้ app ที่เรียกใช้ ให้ต้อง allowBackup นะครับ

**Comment by first087** [comment]
ใช้ Android Studio version ไหนครับ

**Comment by piruin** [comment]
ใช้ Intellij IDEA 15.0.4 ครับผม

**Comment by piruin** [comment]
คิดว่าไม่น่าจะเกี่ยวกับ IDE นะครับ  ลองส่งไป Build บน TRAVIS ก็ได้ error แบบเดียวกัน

**Comment by first087** [comment]
อัพเดต Library เป็น v1.2.0 แล้วครับ ลองทดสอบดูครับ

ขอบคุณครับ

**Comment by piruin** [comment]
ได้แล้วครับ ขอบคุณครับ
